name: pbkdf2
version: 2.1.0
author: James Ots <code@jamesots.com>
homepage: https://github.com/jamesots/pbkdf2
description: Implementation of PBKDF2 key derivation function
environment:
  # Works in Dart 1 (starting with 1.20.1), and works in Dart 2.
  sdk: '>=1.20.1 <3.0.0'
dependencies:
  crypto: '>=2.0.1 <3.0.0'
dev_dependencies:
  test: "^1.3.0"
