name: pbkdf2
version: 0.1.0
author: James Ots <code@jamesots.com>
homepage: https://github.com/jamesots/pbkdf2
description: Implementation of PBKDF2 key derivation function
dependencies:
  crypto: '>=2.0.1 <3.0.0'
dev_dependencies:
  test: '>=0.12.20+3 <0.13.0'
