name: pbkdf2ns
version: 0.0.1
author: James Ots <code@jamesots.com>
homepage: https://github.com/G0mb/pbkdf2
description: Implementation of PBKDF2 key derivation function
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  crypto: ^3.0.1
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
